include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: true # print文の禁止
    prefer_single_quotes: true # シングルクオートのみを使用
    always_use_package_imports: true # 相対パスでのインポート禁止
    avoid_annotating_with_dynamic: true # dynamicで型を注釈することを避ける
    unused_import: true # 未使用のimportを避ける
    unused_local_variable: true # 未使用のローカル変数を避ける
